apiVersion: apps/v1
kind: Deployment
metadata:
  name: netbankuser-deployment
  labels:
    app: netbankuser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netbankuser
  template:
    metadata:
      labels:
        app: netbankuser
    spec:
      containers:
      - name: netbankuser
        image: netbankuser:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: JWT_Secret
          valueFrom:
            secretKeyRef:
              name: geral-secrets
              key: JWT_Secret
        - name: ASPNETCORE_ENVIRONMENT
          value: Development      
        - name: ConnectionStrings__DefaultValue
          valueFrom:
            secretKeyRef:
              name: users-secrets
              key: ConnectionStrings__DefaultValue
---
apiVersion: v1
kind: Service
metadata:
  name: netbankuser-service
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32000
  selector:
    app: netbankuser