apiVersion: v1
kind: Secret
metadata:
  name: users-secrets
type: Opaque
data:
  ConnectionStrings__DefaultValue: RGF0YSBTb3VyY2U9c3Fsc2VydmVyLXNlcnZpY2UubmV0YmFuay5zdmMuY2x1c3Rlci5sb2NhbCwxNDMzO0RhdGFiYXNlPU5ldEJhbmtVc2VycztVc2VyIElkPXNhO1Bhc3N3b3JkPVlvdXJTdHJvbmdAUGFzc3cwcmQ7VHJ1c3RTZXJ2ZXJDZXJ0aWZpY2F0ZT1UcnVl
  